# Config for Dependabot updates. See Documentation here:
# https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  # Update GitHub actions in workflows
  - package-ecosystem: "github-actions"
    directory: "/"
    # Every weekday
    schedule:
      interval: "daily"
    groups:
      github-actions:
        patterns:
          - "*"

  # Enable version updates for Gradle dependencies
  - package-ecosystem: "gradle"
    directory: "/"
    schedule:
      interval: "weekly"
    ignore:
      - dependency-name: "*"
        update-types:
          - "version-update:semver-major"
    groups:
      gradle-minor-patch:
        update-types:
          - "minor"
          - "patch"
