# .pre-commit-config.yaml
exclude: "^app/build/|^build/|^\\.gradle/|^\\.idea/|^\\.git/|^node_modules/"
default_stages: [pre-commit]
minimum_pre_commit_version: "3.2.0"

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-json
      - id: check-toml
      - id: check-xml
      - id: check-yaml
      - id: check-case-conflict
      - id: check-added-large-files
      - id: detect-private-key

  - repo: local
    hooks:
      - id: ktlint-gradle
        name: ktlint (Gradle plugin)
        entry: scripts/ktlint-check.sh
        language: script
        pass_filenames: false
        files: \.(kt|kts)$

  - repo: https://github.com/oxipng/oxipng
    rev: v9.1.5
    hooks:
      - id: oxipng
        name: Image Compression
        args: ["-q", "-o", "2", "-s", "--ng"]

# sets up .pre-commit-ci.yaml to ensure pre-commit dependencies stay up to date
default_install_hook_types: [pre-commit, prepare-commit-msg]
ci:
  autofix_commit_msg: "chore: Auto fix by pre-commit hooks [skip changelog]"
  autofix_prs: true
  autoupdate_commit_msg: "chore: Auto update by pre-commit hooks [skip changelog]"
